[rules.esc_color_basic]
from = '\x1b\[\d{1,2}m'
to = ''

[rules.esc_color_enhanced]
from = '\x1b\[\d{2};\d;[nrgb;]+m'
to = ''

[rules.esc_color_with_weight]
from = '\x1b\[\d{1,2};(?:\d{1,2};?){1,2}m'
to = ''

[_config]
